Fix Error: Cannot find module 'redux-devtools-extension'
    2017-07-11T18:03:16.156801+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:438:15)

    2017-07-11T18:03:16.156815+00:00 app[web.1]:     at Function.Module._load (module.js:386:25)

    2017-07-11T18:03:16.156816+00:00 app[web.1]:     at Module.require (module.js:466:17)

    2017-07-11T18:03:16.156816+00:00 app[web.1]:     at require (internal/module.js:20:19)

    2017-07-11T18:03:16.156823+00:00 app[web.1]:     at Object.<anonymous> (/app/app/store/configureStore.js:10:1)

    2017-07-11T18:03:16.156824+00:00 app[web.1]:     at Module._compile (module.js:541:32)

    2017-07-11T18:03:16.156824+00:00 app[web.1]:     at loader (/app/node_modules/babel-register/lib/node.js:144:5)

    2017-07-11T18:03:16.156829+00:00 app[web.1]:     at Object.require.extensions.(anonymous function) [as .js] (/app/node_modules/babel-register/lib/node.js:154:7)

    2017-07-11T18:03:16.156830+00:00 app[web.1]:     at Module.load (module.js:456:32)

    2017-07-11T18:03:16.156831+00:00 app[web.1]:     at tryModuleLoad (module.js:415:12)

    2017-07-11T18:03:16.156831+00:00 app[web.1]:     at Function.Module._load (module.js:407:3)

    2017-07-11T18:03:16.156832+00:00 app[web.1]:     at Module.require (module.js:466:17)

    2017-07-11T18:03:16.156832+00:00 app[web.1]:     at require (internal/module.js:20:19)

    2017-07-11T18:03:16.156833+00:00 app[web.1]:     at Object.<anonymous> (/app/server.js:33:22)

    2017-07-11T18:03:16.156833+00:00 app[web.1]:     at Module._compile (module.js:541:32)

    2017-07-11T18:03:16.156836+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:550:10)